In [1]:
import requests
import re
import pypinyin as py
import numpy as np
import pandas as pd

# 各个包的用途概述

- 导入requests用于html的爬取
- 导入re用于正则表达式的筛选
- pypinyin库来自github：https://github.com/mozillazg/python-pinyin
- numpy用于将pypinyin生成的二维array转换为一维array
- pandas用于将numpy生成的一维array转换为list

In [2]:
url='http://www.360doc.com/content/16/0419/10/877149_551849520.shtml'
r = requests.get(url)
r.encoding = 'utf-8'

- 原始数据来自360doc
- r作为获取网络内容，用UTF-8进行编码

In [3]:
s_name = re.findall('[\u4e00-\u9fa5]{1,3}市', r.text)
s_name = list(set(s_name))
shi = []
for i in s_name:
    shi.append(i[:-1])
shi_removed = shi.remove('中国省')
shi_removed = shi.remove('国各省')
shi_removed = shi.remove('县级')
shi_removed = shi.remove('辖地级')
shi_removed = shi.remove('县个级')
shi_removed = shi.remove('全国省')

shi

['肥城',
 '保定',
 '井冈山',
 '黄山',
 '九江',
 '什邡',
 '县铜仁',
 '汕头',
 '海阳',
 '卫辉',
 '新乡',
 '孝感',
 '眉山',
 '宁德',
 '大连',
 '韶山',
 '台北',
 '都江堰',
 '简阳',
 '天津',
 '华阴',
 '新余',
 '莱州',
 '合山',
 '大冶',
 '吉首',
 '晋城',
 '都匀',
 '北流',
 '景德镇',
 '宣威',
 '马鞍山',
 '南昌',
 '湖州',
 '南康',
 '冷水江',
 '万源',
 '个地级',
 '永安',
 '菏泽',
 '调兵山',
 '思茅',
 '瑞安',
 '达州',
 '福鼎',
 '临汾',
 '固原',
 '黄石',
 '华蓥',
 '明光',
 '五指山',
 '桂林',
 '金昌',
 '庆阳',
 '姜堰',
 '桃园',
 '醴陵',
 '桐城',
 '南宁',
 '日照',
 '个县级',
 '松滋',
 '楚雄',
 '孟州',
 '高要',
 '崇州',
 '重庆',
 '喀什',
 '舞钢',
 '威海',
 '青州',
 '武穴',
 '上虞',
 '铜陵',
 '瑞金',
 '包头',
 '扬中',
 '乐清',
 '芜湖',
 '奉化',
 '漯河',
 '肇庆',
 '句容',
 '淮北',
 '增城',
 '湘潭',
 '潞城',
 '枣庄',
 '广安',
 '安庆',
 '信宜',
 '邢台',
 '雅安',
 '彰化',
 '内江',
 '栖霞',
 '潍坊',
 '北票',
 '荣成',
 '龙岩',
 '根河',
 '玉溪',
 '兴义',
 '文登',
 '阆中',
 '荆州',
 '临清',
 '涿州',
 '瓦房店',
 '台山',
 '宜城',
 '麻城',
 '安国',
 '衡阳',
 '长乐',
 '兰溪',
 '济宁',
 '合川',
 '敦煌',
 '东莞',
 '贵溪',
 '宁国',
 '石河子',
 '淄博',
 '安康',
 '保山',
 '任丘',
 '郑州',
 '界首',
 '塔城',
 '上饶',
 '洪江',
 '开平',
 '洪湖',
 '偃师',
 '衡水',
 '涟源',
 '平顶山',
 '石嘴山',
 '日喀则',
 '泰州'

# 结尾为市的地名的获取
- 采用正则表达式'[\u4e00-\u9fa5]{1,3}市',获取所有的市名
- 中国大陆市名多为x市、xx市或者xxx市，比如北京市、哈尔滨市、攀枝花市等，有较规律的命名方式

In [4]:
x_name = re.findall('[\u4e00-\u9fa5]{1,3}县', r.text)
x_name = list(set(x_name))
xian = []
for i in x_name:
	xian.append(i[:-1])
xian

['公安',
 '定南',
 '太谷',
 '崇阳',
 '延庆',
 '新绛',
 '上杭',
 '阜南',
 '抚宁',
 '象州',
 '改则',
 '刚察',
 '海盐',
 '阳曲',
 '顺昌',
 '泗阳',
 '囊谦',
 '会同',
 '云梦',
 '隆尧',
 '云霄',
 '宾阳',
 '武宁',
 '宁津',
 '宝丰',
 '三原',
 '丹巴',
 '盐津',
 '兴业',
 '红河',
 '元谋',
 '武胜',
 '贡觉',
 '山丹',
 '宾川',
 '达日',
 '兴文',
 '突泉',
 '清水',
 '岳普湖',
 '米易',
 '石楼',
 '麦盖提',
 '禄丰',
 '沽源',
 '壤塘',
 '礼泉',
 '靖远',
 '多伦',
 '岢岚',
 '庆元',
 '桐柏',
 '唐海',
 '德庆',
 '金门',
 '吉水',
 '内黄',
 '大竹',
 '鲁甸',
 '浪卡子',
 '新干',
 '崇礼',
 '白朗',
 '蒲城',
 '曲阳',
 '龙游',
 '商城',
 '色达',
 '霍城',
 '灵寿',
 '英山',
 '靖安',
 '远安',
 '松阳',
 '平武',
 '蓬溪',
 '灵璧',
 '昂仁',
 '武邑',
 '札达',
 '广宗',
 '沂源',
 '金塔',
 '威信',
 '连城',
 '上犹',
 '淳安',
 '大悟',
 '静乐',
 '迭部',
 '横山',
 '稻城',
 '陆河',
 '黄陵',
 '台中',
 '永修',
 '德清',
 '汾西',
 '炉霍',
 '大方',
 '从江',
 '凤翔',
 '乌恰',
 '芦山',
 '磐安',
 '湖口',
 '宁陵',
 '兴安',
 '青川',
 '庆城',
 '英吉沙',
 '资溪',
 '边坝',
 '阜城',
 '惠东',
 '谢通门',
 '苍南',
 '曲麻莱',
 '偏关',
 '中阳',
 '汶川',
 '邯郸',
 '新邵',
 '城固',
 '嘉禾',
 '清苑',
 '肥东',
 '黎城',
 '苍溪',
 '麻江',
 '镇安',
 '治多',
 '道孚',
 '延长',
 '察雅',
 '贵德',
 '滨海',
 '马山',
 '临洮',
 '闽清',
 '安塞',
 '新源',


# 结尾为县的地名的获取
- 采用正则表达式'[\u4e00-\u9fa5]{1,3}县',获取所有的县名
- 中国大陆市名多为x市、xx市或者xxx市，比如河北的蓟县、安徽的全椒县、新疆的玛纳斯县等，有较规律的命名方式

In [5]:
q_name = re.findall('[\u4e00-\u9fa5]{2,3}区', r.text)
q_name = list(set(q_name))
qu = []
for i in q_name:
	qu.append(i[:-1])
qu.remove('国地名')
qu.remove('各省市')
qu.remove('个市辖')
qu.remove('族自治')
qu.remove('省行政')
qu.remove('省市县')
qu.remove('个地')
qu.remove('尔自治')
qu.remove('别行政')
qu.remove('藏自治')
qu.remove('古自治')
qu.remove('万山特')
qu.remove('六枝特')

qu.append('香港')
qu.append('西藏')
qu.append('澳门')
qu.append('新疆')
qu.append('宁夏')
qu.append('广西')

qu

['北碚',
 '深水埗',
 '河西',
 '长寿',
 '津南',
 '塘沽',
 '观塘',
 '和平',
 '沙坪坝',
 '房山',
 '昌平',
 '黔江',
 '平谷',
 '东丽',
 '南开',
 '双桥',
 '石景山',
 '江北',
 '个特',
 '元朗',
 '权性地',
 '离岛',
 '武清',
 '农架林',
 '西贡',
 '东城',
 '万盛',
 '河北',
 '中西',
 '荃湾',
 '西城',
 '崇文',
 '红桥',
 '汉沽',
 '南岸',
 '大港',
 '北辰',
 '渝北',
 '宝坻',
 '通州',
 '门头沟',
 '大渡口',
 '大兴',
 '西青',
 '九龙坡',
 '怀柔',
 '市辖',
 '涪陵',
 '顺义',
 '丰台',
 '海淀',
 '个林',
 '巴南',
 '大埔',
 '宣武',
 '万州',
 '九龙城',
 '屯门',
 '葵青',
 '湾仔',
 '油尖旺',
 '河东',
 '沙田',
 '朝阳',
 '渝中',
 '黄大仙',
 '香港',
 '西藏',
 '澳门',
 '新疆',
 '宁夏',
 '广西']

# 结尾为区的地名的获取
- 采用正则表达式'[\u4e00-\u9fa5]{1,3}区',获取所有的县名
- 中国大陆市名多为xx区或者xxx区，比如北京的朝阳区、重庆的九龙坡区等，有较规律的命名方式
- 另外在本例中，html中有较多的干扰内容，如国地名、各省市、个市辖等，需要手动一一剔除

In [6]:
all_name = list(set(shi+xian+qu))
all_name = np.reshape(all_name,-1)
all_name

array(['光泽', '泗洪', '武鸣', ..., '天津', '仙桃', '牟定'], dtype='<U3')

# 将所有的市、县、区地名集合起来
- 然后用set和list方法将其**去重**
- 然后将其转换为array，方便之后用pandas生成dataframe

In [7]:
len(all_name)

1920

# 一共提取1920个地名

In [8]:
all_pinyin = py.pinyin(all_name)
all_pinyin = np.reshape(all_pinyin,-1)
all_pinyin

array(['guāng', 'zé', 'sì', ..., 'táo', 'móu', 'dìng'], dtype='<U6')

# 用Github上的pypinyin包
- 用py.pinyin()函数，得到所有汉字对应的拼音
- 用np.reshape()函数，将pypinyin返回的二维array，reshape成一维array，方便之后操作

In [9]:
len(all_pinyin)

3940

# 一共获取了3940个拼音

In [10]:
word_length = []
for i in all_name:
    word_length.append(len(i))
word_length = np.array(word_length)
word_length

array([2, 2, 2, ..., 2, 2, 2])

# 地名非等长的解决办法
- 有的地名是两个字，如深圳。
- 有的地名是三个字，如哈尔滨
- 通过计算每一个地名的字符串长度，实现地名的第一个字和最后一个字的拼音向对应

# 实现首字的拼音和尾字的拼音的对应，是形成押韵的关键算法

In [11]:
len(word_length)

1920

# 验证了地名长度的个数和地名的个数一样都是1920

In [12]:
count = 0
end_position = []
for i in word_length:
    count+=i
    end_position.append(count)
end_position = np.array(end_position)
end_position

array([   2,    4,    6, ..., 3936, 3938, 3940])

# 对尾拼音的定位
- **通过引入count**
- 循环叠加地名的长度，实现尾拼音的定位

In [13]:
len(end_position)

1920

In [14]:
front_position = [m - n + 1 for m,n in zip(end_position,word_length)] 
front_position = np.array(front_position)
front_position

array([   1,    3,    5, ..., 3935, 3937, 3939])

# 头拼音的定位
- 通过尾拼音的定位
- 地名的长度
- 定位出头拼音的坐标

In [15]:
front_pinyin = []
for i in front_position:
    front_pinyin.append(all_pinyin[i - 1])
front_pinyin = np.reshape(front_pinyin,-1)
front_pinyin

array(['guāng', 'sì', 'wǔ', ..., 'tiān', 'xiān', 'móu'], dtype='<U6')

# 头拼音列表的生成
- 有了头拼音的坐标
- 通过循环索引，便能够生成头拼音的列表

In [16]:
end_pinyin = []
for i in end_position:
    end_pinyin.append(all_pinyin[i - 1])
end_pinyin = np.reshape(end_pinyin,-1)
end_pinyin

array(['zé', 'hóng', 'míng', ..., 'jīn', 'táo', 'dìng'], dtype='<U6')

# 同理：生成尾列表

In [17]:
df = pd.DataFrame(all_name,np.arange(len(all_name)))

df[1] = front_pinyin
df[2] = end_pinyin
df.columns = ["地名","头拼音","尾拼音"]
df

地名    头拼音    尾拼音
0      光泽  guāng     zé
1      泗洪     sì   hóng
2      武鸣     wǔ   míng
3      揭东    jiē   dōng
4      龙川   lóng  chuān
5      犍为   qián    wéi
6      彭山   péng   shān
7      荣成   róng  chéng
8      曲沃     qū     wò
9      潜山   qián   shān
10     丹凤    dān   fèng
11     潼南   tóng    nán
12     赤城    chì  chéng
13     江永  jiāng   yǒng
14     天水   tiān   shuǐ
15     班戈    bān     gē
16     凌云   líng    yún
17     三台    sān    tái
18    国省市    guó    shì
19     句容     jù   róng
20     富宁     fù   níng
21    都江堰     dū    yàn
22     江都  jiāng     dū
23     龙门   lóng    mén
24     栾川   luán  chuān
25     汉沽    hàn     gū
26     贵德    guì     dé
27     深圳   shēn   zhèn
28     谷城     gǔ  chéng
29     华蓥    huá   yíng
...   ...    ...    ...
1890   永定   yǒng   dìng
1891   镇平   zhèn   píng
1892   那曲     nà     qū
1893   惠州    huì   zhōu
1894   武清     wǔ   qīng
1895   霍城    huò  chéng
1896   琼结  qióng    jié
1897   邹城    zōu  chéng
1898   册亨     cè   hēng
1899   沅江   yuán  jiāng
1900   达日     dá     rì
1901   罗江    luó  jiāng
1902   江陵  jiāng   líng
1903   甘孜    gān     zī
1904  深水埗   shēn     bù
1905   徐闻     xú    wén
1906   海兴    hǎi   xìng
1907   建湖   jiàn     hú
1908   眉山    méi   shān
1909   大港     dà   gǎng
1910   沙田    shā   tián
1911   扶沟     fú    gōu
1912   来宾    lái    bīn
1913   岳池    yuè    chí
1914   衡阳   héng   yáng
1915   微山    wēi   shān
1916   乐至     lè    zhì
1917   天津   tiān    jīn
1918   仙桃   xiān    táo
1919   牟定    móu   dìng

[1920 rows x 3 columns]

# 使用pandas，让数据表示更直观

In [18]:
place_list = df['地名'].tolist()
place_list

['光泽',
 '泗洪',
 '武鸣',
 '揭东',
 '龙川',
 '犍为',
 '彭山',
 '荣成',
 '曲沃',
 '潜山',
 '丹凤',
 '潼南',
 '赤城',
 '江永',
 '天水',
 '班戈',
 '凌云',
 '三台',
 '国省市',
 '句容',
 '富宁',
 '都江堰',
 '江都',
 '龙门',
 '栾川',
 '汉沽',
 '贵德',
 '深圳',
 '谷城',
 '华蓥',
 '平遥',
 '定州',
 '西城',
 '宜都',
 '龙游',
 '平阴',
 '宁河',
 '丹棱',
 '博野',
 '峡江',
 '鹿邑',
 '米易',
 '个地级',
 '金湖',
 '辉',
 '石首',
 '三明',
 '吴忠',
 '嘉禾',
 '盐城',
 '安阳',
 '滦平',
 '建水',
 '洛川',
 '蓬安',
 '高台',
 '松溪',
 '淮安',
 '陇西',
 '璧山',
 '靖西',
 '大兴',
 '江孜',
 '五寨',
 '太白',
 '万全',
 '合浦',
 '宁武',
 '贺兰',
 '黑山',
 '两当',
 '罗定',
 '拜城',
 '盐山',
 '遂川',
 '宁夏',
 '玉门',
 '固镇',
 '疏附',
 '沙坪坝',
 '六安',
 '崇仁',
 '莱西',
 '垣曲',
 '北宁',
 '周口',
 '赤峰',
 '巴塘',
 '揭阳',
 '西畴',
 '茶陵',
 '台山',
 '衡水',
 '宜章',
 '双峰',
 '宁乡',
 '仪征',
 '临洮',
 '镇巴',
 '沂源',
 '汉阴',
 '宕昌',
 '利辛',
 '绥阳',
 '葫芦岛',
 '呼图壁',
 '剑河',
 '全南',
 '涿鹿',
 '涿州',
 '云霄',
 '合川',
 '滨海',
 '恩平',
 '民权',
 '洱源',
 '武胜',
 '广河',
 '新绛',
 '弋阳',
 '井研',
 '青岛',
 '石阡',
 '蓝田',
 '庆城',
 '九寨沟',
 '古自治',
 '洪泽',
 '万年',
 '拉萨',
 '芦山',
 '怀宁',
 '武隆',
 '锦州',
 '大姚',
 '平谷',
 '肇庆',
 '荆州',
 '靖安',
 '滦南',
 '万盛',
 '凌源',

# 最终分别生成三个包含地名、头拼音、尾拼音的列表，便于检索

In [19]:
head_pinyin_list = df['头拼音'].tolist()
head_pinyin_list

['guāng',
 'sì',
 'wǔ',
 'jiē',
 'lóng',
 'qián',
 'péng',
 'róng',
 'qū',
 'qián',
 'dān',
 'tóng',
 'chì',
 'jiāng',
 'tiān',
 'bān',
 'líng',
 'sān',
 'guó',
 'jù',
 'fù',
 'dū',
 'jiāng',
 'lóng',
 'luán',
 'hàn',
 'guì',
 'shēn',
 'gǔ',
 'huá',
 'píng',
 'dìng',
 'xī',
 'yí',
 'lóng',
 'píng',
 'níng',
 'dān',
 'bó',
 'xiá',
 'lù',
 'mǐ',
 'gè',
 'jīn',
 'huī',
 'shí',
 'sān',
 'wú',
 'jiā',
 'yán',
 'ān',
 'luán',
 'jiàn',
 'luò',
 'péng',
 'gāo',
 'sōng',
 'huái',
 'lǒng',
 'bì',
 'jìng',
 'dà',
 'jiāng',
 'wǔ',
 'tài',
 'wàn',
 'hé',
 'níng',
 'hè',
 'hēi',
 'liǎng',
 'luó',
 'bài',
 'yán',
 'suì',
 'níng',
 'yù',
 'gù',
 'shū',
 'shā',
 'lù',
 'chóng',
 'lái',
 'yuán',
 'běi',
 'zhōu',
 'chì',
 'bā',
 'jiē',
 'xī',
 'chá',
 'tái',
 'héng',
 'yí',
 'shuāng',
 'níng',
 'yí',
 'lín',
 'zhèn',
 'yí',
 'hàn',
 'dàng',
 'lì',
 'suí',
 'hú',
 'hū',
 'jiàn',
 'quán',
 'zhuō',
 'zhuō',
 'yún',
 'hé',
 'bīn',
 'ēn',
 'mín',
 'ěr',
 'wǔ',
 'guǎng',
 'xīn',
 'yì',
 'jǐng',
 'qīng',
 'shí'

In [ ]:
end_pinyin_list = df['尾拼音'].tolist()
end_pinyin_list

['zé',
 'hóng',
 'míng',
 'dōng',
 'chuān',
 'wéi',
 'shān',
 'chéng',
 'wò',
 'shān',
 'fèng',
 'nán',
 'chéng',
 'yǒng',
 'shuǐ',
 'gē',
 'yún',
 'tái',
 'shì',
 'róng',
 'níng',
 'yàn',
 'dū',
 'mén',
 'chuān',
 'gū',
 'dé',
 'zhèn',
 'chéng',
 'yíng',
 'yáo',
 'zhōu',
 'chéng',
 'dōu',
 'yóu',
 'yīn',
 'hé',
 'léng',
 'yě',
 'jiāng',
 'yì',
 'yì',
 'jí',
 'hú',
 'huī',
 'shǒu',
 'míng',
 'zhōng',
 'hé',
 'chéng',
 'yáng',
 'píng',
 'shuǐ',
 'chuān',
 'ān',
 'tái',
 'xī',
 'ān',
 'xī',
 'shān',
 'xī',
 'xīng',
 'zī',
 'zhài',
 'bái',
 'quán',
 'pǔ',
 'wǔ',
 'lán',
 'shān',
 'dāng',
 'dìng',
 'chéng',
 'shān',
 'chuān',
 'xià',
 'mén',
 'zhèn',
 'fù',
 'bà',
 'ān',
 'rén',
 'xī',
 'qū',
 'níng',
 'kǒu',
 'fēng',
 'táng',
 'yáng',
 'chóu',
 'líng',
 'shān',
 'shuǐ',
 'zhāng',
 'fēng',
 'xiāng',
 'zhēng',
 'táo',
 'bā',
 'yuán',
 'yīn',
 'chāng',
 'xīn',
 'yáng',
 'dǎo',
 'bì',
 'hé',
 'nán',
 'lù',
 'zhōu',
 'xiāo',
 'chuān',
 'hǎi',
 'píng',
 'quán',
 'yuán',
 'shèng',
 'hé',
 'jiàng

In [ ]:
get_name = input("请输入地名（比如北京）：")
while get_name:
    if get_name == 'QUIT':
        exit()
    else:
        if get_name in place_list:
            print("存在这个地名\n")
            if end_pinyin_list[place_list.index(get_name)] in head_pinyin_list:
                print('并且存在后继地名，后继城市有如下：\n')
                place_count = 0
                for i in place_list:
                    if end_pinyin_list[place_list.index(get_name)] == head_pinyin_list[place_list.index(i)]:
                        place_count+=1
                        print(place_count,i)
                print('选择一个地名来继续地名接龙,输入其中一个可能的地名：')
                get_name = input('哪一个地名你选择？退出请输入QUIT')
            else:
                print('但是不存在后继地名,请换一个地名重新开始。')
                get_name = input()
        else:
            print("不存在这个地名")
            print('但是不存在后继地名,请换一个地名重新开始。')
            get_name = input()



请输入地名（比如北京）：QUIT


# 最终的逻辑部分